name: .NET Core

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build --configuration Release
