name: .NET Core

on: [push]

jobs:
  build:
    stage: build
    script:
      - dotnet build Gcsb.Connect.AuditLog.sln\Gcsb.Connect.AuditLog.sln
    only:
      refs:
        - master
          
  test:
    stage: test
    script:
      - dotnet test Gcsb.Connect.AuditLog.sln\Gcsb.Connect.AuditLog.sln
    only:
      refs:
        - master
